on:
  #schedule:
    #- cron:  '0 18 * * 4'
  workflow_dispatch:

name: buildx
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - id: Check VER
        run: | 
          latest_version=$(curl -s "https://api.github.com/repos/XTLS/Xray-core/releases/latest" | grep "tag_name" | cut -d\" -f4 | sed -e "s/^v//" -e "s/-.$//" | cut -d"v" -f 2)
          test -f x && current_version=$(./x version | cut -d" " -f 1 | cut -d"v" -f 2)
          if [[ "${latest_version}" == "${current_version}" ]]; then exit 1; fi
          
      - name: Set variables
        run: |
          echo "GOLANG=$(wget -qO- https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep 'version' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
        shell: bash

      - name: Install Golang
        uses: actions/setup-go@v3
        with: 
          go-version: ${{ env.GOLANG }}

      - name: Start Build
        run: |
          git clone https://github.com/XTLS/Xray-core.git 
          cd Xray-core && go mod download
          CGO_ENABLED=0 go build -o x -trimpath -ldflags "-s -w -buildid=" ./main
          mv x ../
          rm -rf ../Xray-core

      - name: Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
